

USE PRACTICE;

--If need to create an alphanumerical IDs

CREATE FUNCTION AID (@C AS CHAR(1), @I AS INT)
RETURNS CHAR(5)
AS
BEGIN

		DECLARE @ID AS CHAR(5);

		IF @I<10
		SET @ID = CONCAT(@C,'000',@I);

		ELSE IF @I<100
		SET @ID = CONCAT(@C, '00', @I);

		ELSE IF @I<1000
		SET @ID = CONCAT(@C, '0', @I);

		ELSE
		SET @ID = 'NA';

		RETURN @ID;

END;

SELECT DBO.AID('E',2);
SELECT DBO.AID('C',222);
DROP FUNCTION AID;


--To create Alpha numeric IDs with SEQUENCE, USER DEFINED FUNC & PROCEDURE.

CREATE SEQUENCE PRACSEQ
AS INT
START WITH 1
INCREMENT BY 1;

CREATE TABLE EMP_PRAC
(EID CHAR(5), NAME VARCHAR(30), AGE INT);

CREATE FUNCTION AID (@C AS CHAR(1),@I AS INT)
RETURNS CHAR(5)
AS
BEGIN

			DECLARE @ID AS CHAR(5);
			
			IF @I<10
			SET @ID = CONCAT(@C,'000',@I);

			ELSE IF @I<100
			SET @ID = CONCAT(@C,'00',@I);

			ELSE IF @I<1000
			SET @ID = CONCAT(@C,'0',@I);

			ELSE 
			SET @ID = 'NA';

			RETURN @ID;
END;

CREATE PROCEDURE PRO_AID_PRAC @N AS VARCHAR(30), @A AS INT
AS
BEGIN

			DECLARE @ID AS CHAR(5);
			DECLARE @I AS INT;

			SET @I = (NEXT VALUE FOR PRACSEQ);
			SET @ID = DBO.AID('C',@I);

			INSERT INTO EMP_PRAC
			VALUES(@ID,@N,@A);

			SELECT * FROM EMP_PRAC;

END;

PRO_AID_PRAC 'BRITTO', '25';