USE DEMO;

--USER DEFINED FUNCTIONS :

--Function to generate mail id
--with f letter of f name
--with f letter of l name
--last three digits of EID
--@RCG.COM

SELECT * FROM EMP;
SELECT * FROM EMP_SAL;

CREATE FUNCTION EMPMAIL(@I AS CHAR(5), @N AS VARCHAR(20), @D AS VARCHAR(20))
RETURNS VARCHAR(100)
AS
BEGIN
			DECLARE @EM AS VARCHAR(100);
			DECLARE @L AS INT;
			DECLARE @S AS INT;
			DECLARE @LN AS VARCHAR(20);
			
			SET @L = LEN(@N);
			SET @S = CHARINDEX(' ',@N);
			SET @LN = SUBSTRING(RIGHT(@N,LEN(@N) - @S),1,1);
			SET @EM = UPPER(CONCAT(LEFT(@N,1),@LN,RIGHT(@I,3),'@', @D, '.COM'));

			RETURN @EM;

END;

SELECT DBO.EMPMAIL('E0001', 'SHALIN BRITTO', 'RCG');


--Function to RETURN EID,NAME,DESI,DEPT,SALARY of the Employees with Specific DEPT

SELECT * FROM E_1;
SELECT * FROM E_SAL;

CREATE FUNCTION EMPDPT(@D AS VARCHAR(10))
RETURNS TABLE
AS

	RETURN(SELECT E_1.EID,NAME,DEPT,DESI,SALARY FROM E_1
			INNER JOIN E_SAL
			ON E_1.EID = E_SAL.EID
			WHERE DEPT = @D);

SELECT * FROM DBO.EMPDPT('IT');

--Function to display NAME, DEPT, DESI, CITY of the Employees who have Birthdays on February

SELECT * FROM E_1;

ALTER TABLE E_1
ADD DOB DATE;

SELECT * FROM E_1;

UPDATE E_1 SET DOB = '01 FEBRUARY 1998'
WHERE EID = 'E0001';
UPDATE E_1 SET DOB = '10 JANUARY 1998'
WHERE EID = 'E0002';
UPDATE E_1 SET DOB = '22 JANUARY 1998'
WHERE EID = 'E0003';
UPDATE E_1 SET DOB = '25 FEBRUARY 1977'
WHERE EID = 'E0004';
UPDATE E_1 SET DOB = '15 FEBRUARY 1992'
WHERE EID = 'E0005';

SELECT * FROM E_1;
SELECT * FROM E_SAL;

CREATE FUNCTION EDOB()
RETURNS TABLE
AS
		RETURN(SELECT E_1.NAME,DEPT,DESI,CITY FROM E_1
		INNER JOIN E_SAL
		ON E_1.EID = E_SAL.EID
		WHERE MONTH(DOB) = '2');

SELECT * FROM DBO.EDOB();

