
--SQL SUBQUERIES

USE DEMO;

SELECT * FROM EMP;
SELECT * FROM EMP_SAL;
SELECT * FROM E_1;
SELECT * FROM E_SAL;

--Need to display EID,NAME,CITY of GURGOAN employees.

SELECT EID,NAME,CITY FROM EMP WHERE CITY = 'GURGOAN';

--Display EID,NAME,DOJ,DEPT,DESI of all MANAGERS :

SELECT * FROM E_1;
SELECT * FROM E_SAL;

ALTER TABLE E_1
ADD DOJ DATE;

UPDATE E_1 SET DOJ = '12 MARCH 2019' WHERE EID = 'E0001';

UPDATE E_1 SET DOJ = '15 JANUARY 2020' WHERE EID = 'E0002';

UPDATE E_1 SET DOJ = '22 APRIL 2019' WHERE EID = 'E0003';

UPDATE E_1 SET DOJ = '2 AUGUST 2019' WHERE EID = 'E0004';

UPDATE E_1 SET DOJ = '21 DECEMBER 2019' WHERE EID = 'E0005';

SELECT * FROM E_1;
SELECT * FROM E_SAL;


SELECT E_1.EID,NAME,DOJ,DEPT,DESI FROM E_1
INNER JOIN E_SAL
ON E_1.EID = E_SAL.EID
WHERE DESI LIKE '%MANAGER';

--Reduce the salary of all DELHI employees by 10%

SELECT * FROM E_SAL;

UPDATE E_SAL SET SALARY = SALARY - SALARY *0.1
WHERE EID in(SELECT EID FROM E_1 WHERE CITY = 'DELHI');

SELECT * FROM E_1;
SELECT * FROM E_SAL;
-----------------------------------------------------------------------------------------------
CREATE PROCEDURE EMPUPD @ID AS CHAR(5), @N AS VARCHAR(20), @C AS VARCHAR(20), @E AS VARCHAR(50),
						@DB AS DATE, @DJ AS DATE,@DPT AS VARCHAR(10), @DSI AS VARCHAR(15),
						@S AS INT
AS
BEGIN
			INSERT INTO E_1
			VALUES(@ID,@N,@C,@E,@DB,@DJ)

			SELECT * FROM E_1;

			INSERT INTO E_SAL
			VALUES(@ID,@DPT,@DSI,@S);

			SELECT * FROM E_SAL;

END;

SELECT * FROM E_1;
SELECT * FROM E_SAL;

EMPUPD 'E0006', 'DAVID', 'DELHI', 'DAVID@GMAIL.COM', '09 FEBRUARY 1997', '10 APRIL 2019',
		'OPS', 'ADMINISTRATOR', '43000';

EMPUPD 'E0007', 'RAMESH GUPTA', 'MUMBAI', 'RAMESHGUPTA@GMAIL.COM', '10 MARCH 1996', '21 JULY 2020',
		'OPS', 'TRAINEE', '23000';


--Display EID,NAME,CITY,DOJ,DEPT,DESI,SALARY of the TEAM MEMBERS of DAVID & RAMESH GUPTA

--First find the EIDs of the names
SELECT EID FROM E_1 WHERE NAME in('DAVID', 'RAMESH GUPTA');

--Find the DEPTS of the names
SELECT DEPT FROM E_SAL 
WHERE EID in(SELECT EID FROM E_1 WHERE NAME in('DAVID', 'RAMESH GUPTA'));

--Find the TEAM MEMBERS EID from the DEPTS

SELECT EID FROM E_SAL
WHERE DEPT in (SELECT DEPT FROM E_SAL 
WHERE EID in(SELECT EID FROM E_1 WHERE NAME in('DAVID','RAMESH GUPTA')));

--Now we can get their full details

SELECT E_1.EID,NAME,CITY,DOJ,DEPT,DESI,SALARY FROM E_1
INNER JOIN E_SAL
ON E_1.EID = E_SAL.EID
WHERE E_1.EID in(SELECT EID FROM E_SAL
WHERE DEPT in (SELECT DEPT FROM E_SAL 
WHERE EID in(SELECT EID FROM E_1 WHERE NAME in('DAVID','RAMESH GUPTA'))));


--Create a TRAINING table and INSERT the EID,NAME,DEPT of the OPS members :

CREATE TABLE TRAINING
(EID CHAR(5), NAME VARCHAR(20), MODULE VARCHAR(10), DEPT VARCHAR(20));

SELECT * FROM TRAINING;

INSERT INTO TRAINING (EID,NAME,DEPT)
(SELECT E_1.EID,NAME,DEPT FROM E_1
INNER JOIN E_SAL
ON E_1.EID = E_SAL.EID
WHERE DEPT = 'OPS');

SELECT * FROM TRAINING;
SELECT * FROM E_SAL;

--Display the salary details of the employees if their salary is more than 35000

SELECT E_1.EID,NAME,SALARY FROM E_1
INNER JOIN E_SAL
ON E_1.EID = E_SAL.EID
WHERE SALARY > 35000 AND EXISTS(SELECT EID FROM E_SAL WHERE SALARY > 35000);